name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  test-customer-identity:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: customer-identity-service

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Creer fichier .env
        run: |
          echo "IDENTITY_DB_HOST=127.0.0.1" >> .env
          echo "IDENTITY_DB_PORT=3306" >> .env
          echo "IDENTITY_DB_NAME=customer_identity_db" >> .env
          echo "IDENTITY_DB_USER=customer_identity" >> .env
          echo "IDENTITY_DB_PASS=customer_identity" >> .env

      - name: Run tests
        working-directory: customer-identity-service/src
        run: pytest

  test-commerce:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: commerce-service

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Creer fichier .env
        run: |
          echo "COMMERCE_DB_HOST=127.0.0.1" >> .env
          echo "COMMERCE_DB_PORT=3306" >> .env
          echo "COMMERCE_DB_NAME=commerce_db" >> .env
          echo "COMMERCE_DB_USER=commerce" >> .env
          echo "COMMERCE_DB_PASS=commerce" >> .env
          echo "REDIS_HOST=127.0.0.1" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "REDIS_DB=0" >> .env

      - name: Run tests
        working-directory: commerce-service/src
        run: pytest
